[package]
name = "x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.9.4"
lettre_email = "0.9.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
encoding_rs = "0.8"
