name: Rust CI and Deploy

on:
  push:
    branches:
      - main # 监听 main 分支的推送

jobs:
  build-and-deploy:
    environment:
      name: 42tr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: export DATABASE_URL=${{ secrets.DATABASE_URL }} && sudo apt-get install musl-tools && rustup target add x86_64-unknown-linux-musl && cargo build --target x86_64-unknown-linux-musl --release

      - name: Create directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/x/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "target/x86_64-unknown-linux-musl/release/x"
          target: "/home/x/"

      - name: Deploy to CentOS server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/x/
            killall x
            rm -rf x
            mv target/x86_64-unknown-linux-musl/release/x ./
            chmod 777 x
            rm -rf target
            export EMAIL_AUTHORIZE_CODE=${{ secrets.EMAIL_AUTHORIZE_CODE }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            nohup ./x > log.txt 2>&1 &

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3.1.3
        with:
          name: rust-package-distributions
          path: target/x86_64-unknown-linux-musl/release/x
