name: Rust CI and save

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment:
      name: 42tr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build project for Raspberry Pi (ARM64)
        run: |
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          cross build --target aarch64-unknown-linux-musl --release --env DATABASE_URL

      - name: Create directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/aarch64/x/

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "target/aarch64-unknown-linux-musl/release/x"
          target: "/home/aarch64/x/"
